esphome:
  name: "udp-multicast-can-interface"
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

wifi:
  power_save_mode: none
  <<: !include {file: wifi.yaml}

api:

logger:

external_components:
  - source: github://mrk-its/esphome-canbus-udp-multicast

canbus:
  - platform: esp32_can
    id: esp32_can_bus
    rx_pin: GPIO5
    tx_pin: GPIO4
    can_id: 0
    bit_rate: 125kbps

  - platform: canbus_udp_multicast
    id: udp_multicast
    can_id: 0
    canbus_id: esp32_can_bus  # physical canbus component defined above
    multicast_ip: 232.10.11.12

interval:
  - interval: 5seconds
    then:
      - canbus.send:
          data: [7]
          canbus_id: udp_multicast
